spring:
  application:
    name: siungongsi

  doc:
    swagger-ui:
      enabled: true
      path: /swagger-ui  # Swagger UI 경로 변경
    api-docs:
      enabled: true
      path: /v3/api-docs  # API 문서 경로 설정
